defaults: &defaults
  config:
    address: smtp.163.com
    port: 25
    user_name: zhangcaiyanbeyond@163.com
    password: "zcy142322"
    authentication: :login
    enable_starttls_auto: false 

development:
  <<: *defaults
  host:
    host: localhost:3000 
    host_only: localhost
    port_only: "3000"

test:
  <<: *defaults

production:
  <<: *defaults
  host:
    host: www.wode521.com
    host_only: www.wode521.com
    port_only: "80"
